# Generated by Django 2.0.5 on 2018-05-07 20:36

import balance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='id',
            field=models.CharField(default=balance.models.id_generator, max_length=6, primary_key=True, serialize=False),
        ),
    ]
