# Generated by Django 2.0.5 on 2018-05-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0003_auto_20180507_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='escrow',
            field=models.IntegerField(default=0),
        ),
    ]
