# Generated by Django 2.0.5 on 2018-05-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
